# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fddd9dc89a2aed1a91a8455b44b41c49"
name = "app-development"
<<<<<<< HEAD
application_url = "https://invitation-donor-athens-haiti.trycloudflare.com"
=======
application_url = "https://queue-detection-vertex-syndication.trycloudflare.com"
>>>>>>> a7a8e453a5796727311340e61b129edaa86d0eed
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "algorithm-with-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_products,read_themes,write_content,write_products,write_themes"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://invitation-donor-athens-haiti.trycloudflare.com/auth/callback",
  "https://invitation-donor-athens-haiti.trycloudflare.com/auth/shopify/callback",
  "https://invitation-donor-athens-haiti.trycloudflare.com/api/auth/callback"
=======
  "https://queue-detection-vertex-syndication.trycloudflare.com/auth/callback",
  "https://queue-detection-vertex-syndication.trycloudflare.com/auth/shopify/callback",
  "https://queue-detection-vertex-syndication.trycloudflare.com/api/auth/callback"
>>>>>>> a7a8e453a5796727311340e61b129edaa86d0eed
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
