# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5979b1355fc1fc33469e698f5e91dabe"
name = "new-testing-app"
handle = "new-testing-app-9"
application_url = "https://junction-motor-omaha-evening.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-store-kazi.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_products"

[auth]
redirect_urls = [
  "https://junction-motor-omaha-evening.trycloudflare.com/auth/callback",
  "https://junction-motor-omaha-evening.trycloudflare.com/auth/shopify/callback",
  "https://junction-motor-omaha-evening.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
