# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3719115214fb2cfb444722b4d203a89e"
name = "SeoFY-TEST-APP"
handle = "seofy-test-app"
application_url = "https://metallica-engines-viewing-packed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "joy-matubber-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_products,read_themes,write_content,write_products,write_themes"

[auth]
redirect_urls = [
  "https://metallica-engines-viewing-packed.trycloudflare.com/auth/callback",
  "https://metallica-engines-viewing-packed.trycloudflare.com/auth/shopify/callback",
  "https://metallica-engines-viewing-packed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
