# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5979b1355fc1fc33469e698f5e91dabe"
name = "app-development-kazi"
handle = "new-testing-app-9"
application_url = "https://rangers-supervisor-contacted-modern.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-store-kazi.myshopify.com"

[auth]
redirect_urls = [
  "https://rangers-supervisor-contacted-modern.trycloudflare.com/auth/callback",
  "https://rangers-supervisor-contacted-modern.trycloudflare.com/auth/shopify/callback",
  "https://rangers-supervisor-contacted-modern.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
