import mongoose from "mongoose";

const htmlCleanerSettingsSchema = new mongoose.Schema(
  {
    shopId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    enabled: {
      // Overall toggle for the HTML cleanup feature
      type: Boolean,
      default: false,
    },
    // Specific meta tags to remove by their 'name' or 'property' attribute
    metaTagsToRemove: {
      type: [String],
      default: [
        "seogid",
        "generator",
        "shopify-digital-wallet",
        "x-shopify-theme",
        "csrf-token",
      ],
    },
    // HTML elements to consider for removal if they are empty AND meet criteria
    emptyElementsToRemove: {
      type: [String],
      default: ["div", "span", "p", "section"],
    },
    // Store regex patterns as strings for attributes to be removed if they are not whitelisted
    attributesToRemovePatterns: {
      type: [String],
      default: [
        "^data-shopify-tracking",
        "^data-mce-",
        "^data-gramm_id",
        "^data-gramm",
        "^data-test-",
        "debug-id",
      ],
    },
    // Option to remove all data-* attributes not explicitly whitelisted below
    removeAllUncategorizedDataAttributes: {
      type: Boolean,
      default: false,
    },
    removeEmptyStyles: {
      // For style=""
      type: Boolean,
      default: true,
    },
    removeHtmlComments: {
      type: Boolean,
      default: true,
    },
    // Basic whitespace collapsing in text nodes and around block elements (use with caution on .liquid files)
    collapseWhitespace: {
      type: Boolean,
      default: false, // Default to false for safety, especially with Liquid
    },
    whitelist: {
      tags: {
        type: [String],
        default: [
          "script",
          "style",
          "template",
          "form",
          "input",
          "select",
          "textarea",
          "button",
          "iframe",
          "link",
          "meta",
          "br",
          "hr",
          "img",
          "canvas",
          "video",
          "audio",
          "pre",
          "code",
          "svg",
          "path",
          "noscript",
        ],
      },
      attributes: {
        type: [String],
        default: [
          "id",
          "class",
          "style",
          "href",
          "src",
          "action",
          "method",
          "type",
          "value",
          "name",
          "rel",
          "target",
          "alt",
          "title",
          "for",
          "role",
          "aria-label",
          "aria-labelledby",
          "aria-describedby",
          "aria-hidden",
          "aria-expanded",
          "aria-controls",
          "aria-live",
          "aria-pressed",
          "aria-checked",
          "aria-selected",
          "aria-current",
          "disabled",
          "readonly",
          "required",
          "checked",
          "selected",
          "pattern",
          "placeholder",
          "autocomplete",
          "media",
          "property",
          "content",
          "charset",
          "http-equiv",
          "itemscope",
          "itemtype",
          "itemprop",
          "datetime",
          "data-section-id",
          "data-section-type",
          "data-shopify-editor-section",
          "data-product-id",
          "data-product-handle",
          "data-variant-id",
          "data-shopify",
          "data-handle",
          "data-value",
          "data-index",
          "data-filter",
          "data-filter-type",
          "data-cart-render",
          "data-cart-static-render",
          "data-ajax-cart-section",
          "data-modal-id",
          "data-modal-target",
          "data-bs-toggle",
          "data-bs-target",
          "data-toggle",
          "data-target",
          "data-component",
          "data-action",
          "data-bind",
          "data-js",
          "data-module",
          "onclick",
          "onsubmit",
          "onchange",
          "onkeyup",
          "onkeydown",
          "onmouseover",
          "onmouseout", // Event handlers
          "viewbox",
          "xmlns",
          "fill",
          "stroke",
          "stroke-width",
          "d", // SVG attributes
        ],
      },
      classes: {
        type: [String],
        default: [
          "shopify-challenge__container",
          "shopify-payment-button__button",
          "product-form",
          "product-form__input",
          "product-form__submit",
          "cart-form",
          "js-",
          "is-active",
          "is-visible",
          "is-hidden",
          "active",
          "hidden",
          "open",
          "no-js", // Common class for JS detection
          "lazyload",
          "lazyloading",
          "lazyloaded", // Common lazyloading classes
        ],
      },
      shopifyRequiredSelectors: {
        type: [String],
        default: [
          'form[action^="/cart"]',
          'form[action^="/account"]',
          'form[action^="/contact"]',
          'form[action*="product_id"]',
          'form[action*="/localization"]',
          'form[action*="/currency"]',
          '[id^="shopify-section-"]',
          ".shopify-payment-button",
          '[data-shopify="payment-button"]',
          "#shopify-content",
          ".product-form",
          "[data-product-form]",
          "[data-productid]",
          '[id^="product-form-"]',
          ".cart-form",
          'script[src*="shopify_common.js"]',
          'script[src*="option_selection.js"]',
          'script[id="shopify-features"]',
          'script[type="application/json"][data-product-json]',
          'meta[name="csrf-token"]',
          'meta[property^="og:"]',
          'meta[name^="twitter:"]',
          'link[rel="canonical"]',
          'link[rel="alternate"]',
          'link[rel="preconnect"]',
          "[data-shopify-editor-section]",
          "[data-shopify-editor-block]",
          "#MainContent",
          "#PageContainer",
          "#cart-drawer",
          "#CartDrawer",
          "[data-section-id][data-section-type]",
          'script[type="application/ld+json"]',
        ],
      },
      commentPatternsToKeep: {
        type: [String],
        default: [
          "^\\[if\\s",
          "^<!\\[endif\\]", // IE conditional comments
          "^eslint-",
          "^stylelint-",
          "^prettier-",
          "^webpackChunkName:",
          "^\\s*global\\s",
          "^\\s*exported\\s", // Common build/linter comments
          "Copyright",
          "license", // License headers
        ],
      },
    },
  },
  {
    timestamps: true,
  }
);

const HtmlCleanerSettings = mongoose.model(
  "HtmlCleanerSettings",
  htmlCleanerSettingsSchema
);

export default HtmlCleanerSettings;
